### ISSUE TITLE
Travellers backpack support

### ISSUE THREAD

**Issue by W4BEPMA** [roidrole/A-Dark-Mode-Addon#6]
pls add dark theme for travellers backpack mod

**Comment by roidrole** [comment]
Pending CF approval. Please tell me if support is satisfactory. Will be added as part of version 1.7.0

**Comment by W4BEPMA** [comment]
and what about integrated terminals support?
![изображение](https://github.com/user-attachments/assets/cf39faaf-6530-4164-b2f1-b97164296aa9)

**Comment by W4BEPMA** [comment]
and travellers backpack looks well

**Comment by roidrole** [comment]
Will be added in 1.8.0!
